### ISSUE TITLE
Can't seem to get it to detect sandbox correctly

### ISSUE THREAD

**Issue by dustinkerstein** [JamesMGreene/sandblaster#6]
I'm running sandblaster in a react app and I can get it to log the object returned by detect(), but regardless of the browser (or the parent domain) I always see these results even though I know some of the domains have the sandbox parameter added:

```
crossOrigin:true
errors:[]
framed:true
resandboxable:false
sandboxAllowances:{forms: null, modals: null, orientationLock: null, pointerLock: null, popups: null, …}
sandboxable:false
sandboxed:null
unsandboxable:false
__proto__:Object
```

I'm running it like: `const result = sandblaster.detect();`

Any idea what could be going on?

**Comment by dustinkerstein** [comment]
Here's what the iFrame looks like when embedded on Twitter:

`<iframe data-src="https://my.panomoments.com/embed/5ac43cd4ecc1fc000f8fef6e" frameborder="0" scrolling="no" allowtransparency="true" sandbox="allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts" src="https://my.panomoments.com/embed/5ac43cd4ecc1fc000f8fef6e?autoplay=1&amp;auto_play=true"></iframe>`

And here's the source Tweet where that iFrame lives - https://twitter.com/tomimpallomeni/status/981377781366800384

**Comment by JamesMGreene** [comment]
If the frame is cross-origin, then nothing else can be correctly detected. The `null` values for the various properties there (most importantly, the `sandboxed` property) means that the state of each cannot be accurately detected.

**Comment by dustinkerstein** [comment]
Ah ok. I was thinking the point of sandblaster was in-fact for cross origin use-cases. Sorry for the misunderstanding.

**Comment by JamesMGreene** [comment]
Unfortunately, browser security is too restrictive to allow that (for obvious reasons, once you think about the potential risks to security, privacy, and user experience).
