### ISSUE TITLE
Sandbox not being detected

### ISSUE THREAD

**Issue by J-Brk** [JamesMGreene/sandblaster#7]
Chrome 67.0.3396.79

Iframe with `sandbox="allow-scripts allow-forms allow-same-origin"`
Results in;

```javascript
{
    crossOrigin: true,
    framed: true,
    resandboxable: false,
    sandboxAllowances: [
        forms: null,
        modals: null,
        orientationLock: null,
        pointerLock: null,
        popups: null,
        popupsToEscapeSandbox: null,
        presentation: null,
        sameOrigin: null,
        scripts: true,
        topNavigation: null,
        topNavigationByUserActivation: null
    ],
    sandboxable: false,
    sandboxed: null,
    unsandboxable: false
}
```

The same iframe without sandbox tag, results in exactly the same parameters.

**Comment by JamesMGreene** [comment]
If the frame is cross-origin, then nothing else can be correctly detected. The `null` values for the various properties there (most importantly, the `sandboxed` property) means that the state of each cannot be accurately detected.
